### PR TITLE
feat:add doc to homepage

### PR DESCRIPTION
**Pull request by BISINIGISHIVANI**
Screenshot 2022-02-15 164134
Screenshot 2022-02-15 164629

### CODE REVIEW

**Comment by aman11s** [comment]
Screenshot 2022-02-14 at 5 35 17 PM

I will suggest you give some spacing to your whole main container and make your navbar sticky which takes whole horizontal space like a div.

**Comment by aman11s** [comment]
Screenshot 2022-02-14 at 5 38 57 PM

- Avatar is breaking

**Comment by aman11s** [comment]
Screenshot 2022-02-14 at 5 40 13 PM

- I'm not pointing out but this looks so packed and congested. So I would suggest you give some spacing to your buttons and this container too.

**Comment by aman11s** [comment]
- Many of your components require spacing. So, I would suggest you check once again and give consistent spacing to your components and your page layout.

**Comment by AtulPant2704** [comment]
Many of your components require padding, you should indent and space out your components properly.

**Review by VishalPatil18 — CHANGES_REQUESTED** [review]
- The code looks fine
- You would need to work more on styling. 
- Also, it is not responsive that is what you would look to work on.
- You could align the `copy-text` button and the input box.
Screenshot 2022-02-14 at 18 51 31

- You could add padding and margins to the sections.
- The buttons could be given more styling and padding.
- The close alert icons and close toast icons could be given a `cursor: pointer;` in order to make them look like clickable elements to the user.
- The card with text overlays color contrast could be improved by giving the text some background with less opacity.
Screenshot 2022-02-14 at 18 54 32
 
- Inputs could be given padding and also better background and border.
- Padding bottom could be given to the whole body as the text on the bottom is very close to the end of the screen.
- There's no footer. You could add one as that helps in better UX.

Finally, a suggestion would be to work on the styling a bit more. TBH, currently, it is not looking that good.
The code looks quite clean. Great work there @BISINIGISHIVANI 👍

**Comment by BISINIGISHIVANI** [comment]
> Screenshot 2022-02-14 at 5 38 57 PM
> 
> * Avatar is breaking

**Review by VishalPatil18 — APPROVED** [review]

**Review by AtulPant2704 — APPROVED** [review]

**Pull request merged**
